In [1]:
import pandas as pd
import numpy as np
import os 
import pickle
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
os.chdir('C:\\Users\\janum\\OneDrive\\Desktop\\')

In [3]:
print (os.getcwd())

C:\Users\janum\OneDrive\Desktop

In [4]:
df=pd.read_csv('parkinsons.data')

In [5]:
X=df.drop(labels=['status','name'],axis=1)
display (X.head())

,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,MDVP:Shimmer(dB),...,MDVP:APQ,Shimmer:DDA,NHR,HNR,RPDE,DFA,spread1,spread2,D2,PPE
0,119.992,157.302,74.997,0.00784,0.00007,0.00370,0.00554,0.01109,0.04374,0.426,...,0.02971,0.06545,0.02211,21.033,0.414783,0.815285,-4.813031,0.266482,2.301442,0.284654
1,122.400,148.650,113.819,0.00968,0.00008,0.00465,0.00696,0.01394,0.06134,0.626,...,0.04368,0.09403,0.01929,19.085,0.458359,0.819521,-4.075192,0.335590,2.486855,0.368674
2,116.682,131.111,111.555,0.01050,0.00009,0.00544,0.00781,0.01633,0.05233,0.482,...,0.03590,0.08270,0.01309,20.651,0.429895,0.825288,-4.443179,0.311173,2.342259,0.332634
3,116.676,137.871,111.366,0.00997,0.00009,0.00502,0.00698,0.01505,0.05492,0.517,...,0.03772,0.08771,0.01353,20.644,0.434969,0.819235,-4.117501,0.334147,2.405554,0.368975
4,116.014,141.781,110.655,0.01284,0.00011,0.00655,0.00908,0.01966,0.06425,0.584,...,0.04465,0.10470,0.01767,19.649,0.417356,0.823484,-3.747787,0.234513,2.332180,0.410335

In [6]:
Y=df['status']
display (Y.head())

0    1
1    1
2    1
3    1
4    1
Name: status, dtype: int64

In [8]:
model=pickle.load(open('deploy_SVM.pkl','rb'))

In [9]:
prediction = model.predict (X)
print ( 'Accuracy ',accuracy_score (Y, prediction))
print ()
print ( 'Classification Report')
print (classification_report  (Y,prediction,zero_division=0))
print ( 'Confusion Matrix')
print (confusion_matrix  (Y,prediction))

Accuracy  0.882051282051282

Classification Report
              precision    recall  f1-score   support

           0       0.90      0.58      0.71        48
           1       0.88      0.98      0.93       147

    accuracy                           0.88       195
   macro avg       0.89      0.78      0.82       195
weighted avg       0.88      0.88      0.87       195

Confusion Matrix
[[ 28  20]
 [  3 144]]

In [12]:
result = pd.concat ([df['status'],pd.DataFrame (prediction,columns = ['Prediction'])],axis =1)
display (result.head(10))

   status  Prediction
0       1           1
1       1           1
2       1           1
3       1           1
4       1           1
5       1           1
6       1           1
7       1           1
8       1           1
9       1           1